name: Laravel Compatibility Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - '.github/workflows/laravel-test.yml'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: L${{ matrix.laravel }} - P${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - laravel: '10.*'
            php: '8.1'
          - laravel: '10.*'
            php: '8.2'
          - laravel: '11.*'
            php: '8.2'
          - laravel: '11.*'
            php: '8.3'

    steps:
    - name: Checkout package
      uses: actions/checkout@v4
      with:
        path: package

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, exif
        coverage: none

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Create Laravel app
      run: |
        composer create-project laravel/laravel app "${{ matrix.laravel }}"
        cd app
        php artisan key:generate

    - name: Install package
      run: |
        cd package
        npm install
        cd ../app
        npm install ../package

    - name: Test encryption compatibility
      run: |
        cd app
        cat > test-encryption.php << 'PHP'
        <?php
        require 'vendor/autoload.php';
        $app = require_once 'bootstrap/app.php';
        $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
        $kernel->bootstrap();

        // Test data
        $testCases = [
            'string' => 'Hello World',
            'number' => 123456,
            'array' => ['key' => 'value'],
            'boolean' => true,
            'null' => null
        ];

        $failed = false;

        foreach ($testCases as $type => $data) {
            // PHP encrypt
            $encrypted = \Crypt::encrypt($data);

            // Node.js decrypt test
            $nodeTest = "
            const { LaravelEncrypter } = require('laravel-node-encryption');
            const enc = new LaravelEncrypter();
            try {
                const decrypted = enc.decrypt('$encrypted');
                console.log('✅ $type test passed');
            } catch (e) {
                console.error('❌ $type test failed:', e.message);
                process.exit(1);
            }
            ";

            file_put_contents('node-test.js', $nodeTest);
            exec('node node-test.js', $output, $returnCode);

            if ($returnCode !== 0) {
                $failed = true;
                echo "❌ Failed to decrypt $type in Node.js\n";
            } else {
                echo "✅ $type: PHP->Node successful\n";
            }
        }

        exit($failed ? 1 : 0);
        PHP

        php test-encryption.php