name: Release Management

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Release Please
      uses: google-github-actions/release-please-action@v4
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: node
        package-name: laravel-node-encryption

    # If release was created, publish to NPM
    - name: Publish to NPM
      if: ${{ steps.release.outputs.release_created }}
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # Notify on success
    - name: Notify Release
      if: ${{ steps.release.outputs.release_created }}
      run: |
        echo "🎉 Released version ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
        echo "📦 View on NPM: https://www.npmjs.com/package/laravel-node-encryption"